#!/bin/bash
echo "======================="
echo " 小橘3号 终端全局指令"
echo "======================="
echo "xiaoju3_start   -> 一键后台启动机器人"
echo "xiaoju3_stop    -> 一键停止机器人"
echo "xiaoju3_restart -> 一键重启机器人"
echo "xiaoju3_link    -> 一键提取日志 (需加链接)"
echo "xiaoju3_push    -> 一键安检并上传代码"
echo "xiaoju3_secret  -> 🍊 密钥与配置一键修改工具"
echo "xiaoju3_dashboard_start -> 一键启动 Web 控制台"
echo "xiaoju3_dashboard_stop  -> 暂停 Web 控制台（需密码）"
echo "xiaoju3_stop_all        -> 一键暂停全部服务（含 HA、NapCat）"
echo "xiaoju3_help    -> 查看此帮助"
echo ""
echo "======================="
echo " 小橘3号 QQ 聊天指令"
echo "======================="
echo "/help           -> 获取机器人菜单"
echo "/gen_log [链接]  -> 生成开发日志"
echo "/send_image [路径] -> 发送图片"
echo "帮我点击手机上的 [图标名] -> 精准控制手机界面"
echo "帮我看看手机屏幕上有什么 -> AI 视觉识别屏幕"
echo ""
echo "======================="
echo " 💡 小橘3号当前能力"
echo "======================="
echo "🧠 本地大脑：天选5 (RTX 4060) 优先，云端兜底"
echo "💓 主动心跳：每60秒自动感知家庭环境"
echo "🤖 精准接管：通过 ADB 原生 UI 解析控制安卓手机"
echo "🏠 万物互联：通过 Home Assistant 控制智能家居"